### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by tvrcgo** [supersheep/wechat-pay#10]
![qq 20150320101150](https://cloud.githubusercontent.com/assets/237062/6744872/9a5bae26-cee9-11e4-80cf-09b3ed082452.png)

用了 wechat-pay 来做微信支付开发，出现下面的问题，请教是什么导致的？
```
TypeError: Cannot read property 'toString' of undefined
   at Payment._signedQuery (/data/www/node_modules/wechat-pay/lib/payment.js:126:30)
   at Payment.unifiedOrder (/data/www/node_modules/wechat-pay/lib/payment.js:151:8)
   at Payment.getBrandWCPayRequestParams (/data/www/node_modules/wechat-pay/lib/payment.js:52:8)
   at /data/www/node-weixin/route/wxpay.js:30:8
   at Layer.handle [as handle_request] (/data/www/node_modules/express/lib/router/layer.js:82:5)
   at next (/data/www/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/data/www/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/data/www/node_modules/express/lib/router/layer.js:82:5)
   at /data/www/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/data/www/node_modules/express/lib/router/index.js:321:12)
```

**Comment by supersheep** [comment]
应该是由于req.ip 或者 req.app.locals.user为undefined吧
