### ISSUE TITLE
body如果有emoji会出现崩溃

### ISSUE THREAD

**Issue by huzhenjie** [supersheep/wechat-pay#33]
body如果有emoji会出现崩溃

信息如下

```
...
Unhandled rejection Error: Invalid character (�) in string: 如何 a%n?🏠 at index 10
    at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLStringifier.js:149:15)
    at XMLStringifier.assertLegalChar (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLStringifier.js:4:59)
    at XMLStringifier.module.exports.XMLStringifier.eleText (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLStringifier.js:28:19)
    at new XMLText (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLText.js:19:35)
    at XMLElement.module.exports.XMLNode.text (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLNode.js:165:15)
    at XMLElement.module.exports.XMLNode.node (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLNode.js:157:15)
    at XMLElement.module.exports.XMLNode.element (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLNode.js:100:28)
    at XMLElement.module.exports.XMLNode.ele (/home/Tinstone-Course-Server/node_modules/xmlbuilder/lib/XMLNode.js:268:19)
    at /home/Tinstone-Course-Server/node_modules/wechat-pay/node_modules/xml2js/lib/xml2js.js:204:37
    at Builder.exports.Builder.Builder.buildObject (/home/Tinstone-Course-Server/node_modules/wechat-pay/node_modules/xml2js/lib/xml2js.js:216:14)
    at Payment.buildXml (/home/Tinstone-Course-Server/node_modules/wechat-pay/lib/payment.js:286:21)
    at Payment._signedQuery (/home/Tinstone-Course-Server/node_modules/wechat-pay/lib/payment.js:188:21)
    at Payment.unifiedOrder (/home/Tinstone-Course-Server/node_modules/wechat-pay/lib/payment.js:205:8)
    at Payment.getBrandWCPayRequestParams (/home/Tinstone-Course-Server/node_modules/wechat-pay/lib/payment.js:53:8)
...
```

**Comment by supersheep** [comment]
related to https://github.com/oozcitak/xmlbuilder-js/issues/77
