### ISSUE TITLE
无法退款，报socket hang up错误

### ISSUE THREAD

**Issue by jypblue** [supersheep/wechat-pay#61]
调用接口，报socket hang up 错误：
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
2018-03-10 15:12:11,299 ERROR 18660 [-/127.0.0.1/-/78ms PUT /api/orders/refund/5155] nodejs.ECONNRESETError: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ECONNRESET'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ECONNRESETError'
pid: 18660
```
请求代码如下：
```
    const refundConfig = {
      out_trade_no: order.o_code,
      out_refund_no: `${order.o_code}_refund`,
      total_fee: 1,
      refund_fee: 1,
    };

    const res = await this.payment().refundPromise(refundConfig);
    console.log(res);

payment() {
    const payment = new Payment(this.app.config.wxPay);
    payment.refundPromise = param => {
      return new Promise((resolve, reject) => {
        payment.refund(param, function(error, result) {
          console.log(error);
          if (error) {
            return reject(error);
          }
          console.log(result);
          resolve(result);
        });
      });
    };

    return payment;
  }

```

**Comment by jinceon** [comment]
今天我也遇到了。我遇到的原因是我没配置证书。
```js
var Payment = require('wechat-pay').Payment;
var initConfig = {
  partnerKey: "<partnerkey>",
  appId: "<appid>",
  mchId: "<mchid>",
  notifyUrl: "<notifyurl>",
  pfx: fs.readFileSync("<location-of-your-apiclient-cert.p12>") //我漏了这行
};
var payment = new Payment(initConfig);
```

**Comment by YuDaChao** [comment]
@jinceon 我配置 请求还是 socket hang up
`const initConfig = {
  partnerKey: "<partnerkey>",
  appId: "<appid>",
  mchId: "<mchid>",
  notifyUrl: "<notifyurl>",
  pfx: fs.readFileSync("<location-of-your-apiclient-cert.p12>",'ascii')
};`
能帮忙看看一吗？感谢🙏

**Comment by jinceon** [comment]
```js
fs.readFileSync("<location-of-your-apiclient-cert.p12>") 

fs.readFileSync("<location-of-your-apiclient-cert.p12>",'ascii') 
```
你抄都能抄错，我还能说什么呢？ @YuDaChao
