### ISSUE TITLE
调用退款接口出错

### ISSUE THREAD

**Issue by conanx2008** [supersheep/wechat-pay#74]
(node:17108) UnhandledPromiseRejectionWarning: Error: not enough data
    at Object.createSecureContext (_tls_common.js:158:19)
    at Object.exports.connect (_tls_wrap.js:1062:48)
    at Agent.createConnection (https.js:117:22)
    at Agent.createSocket (_http_agent.js:227:26)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:268:16)
    at Object.request (http.js:39:10)
    at Object.request (https.js:245:15)
    at Payment._httpsRequest (/Users/conanx/Project/admin/node_modules/wechat-pay/lib/payment.js:178:19)
    at Payment._signedQuery (/Users/conanx/Project/admin/node_modules/wechat-pay/lib/payment.js:264:3)
    at Payment.refund (/Users/conanx/Project/admin/node_modules/wechat-pay/lib/payment.js:297:8)
    at Promise (/Users/conanx/Project/admin/node_modules/wechat-pay/lib/payment.js:503:16)
    at new Promise (<anonymous>)
    at Payment.(anonymous function) [as refund] (/Users/conanx/Project/admin/node_modules/wechat-pay/lib/payment.js:487:16)

我的node.js版本是 8.16.2,
wechat-pay的版本是从npm库里自动下载的
错误定位到
payment.js +178行的请求，麻烦大神能看下是怎么回事？
万分感谢！

**Comment by conanx2008** [comment]
这是我的wechat-pay版本号： 0.3.2 
name": "wechat-pay",
  "version": "0.3.2",
  "description": "wechat payment api for document v3.3.5",
  "main": "index.js",

**Comment by conanx2008** [comment]
是我的问题，我只传了证书的路径，应该传证书的内容，现在已经正常了！
